# Rust code formatting; see https://rust-lang.github.io/rustfmt
edition = "2021"
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
